#!/usr/bin/env node
/**
 * scip-to-expected.ts
 *
 * Reads a SCIP index file (protobuf format) generated by a compiler-backed indexer
 * (e.g., scip-typescript, scip-java, scip-dotnet) and converts it to our expected.json
 * format for benchmark fixture validation.
 *
 * This provides ground-truth file-to-file edges derived from real compiler analysis,
 * eliminating the "heuristic grading heuristic" circular validation problem.
 *
 * Usage:
 *   npx tsx scripts/fixture-tools/scip-to-expected.ts --input path/to/index.scip [--output path/to/expected.json]
 *
 * The script:
 *   1. Deserializes the SCIP protobuf index
 *   2. Builds a symbol → defining-file map from Definition occurrences
 *   3. For each file, finds all non-Definition symbol references
 *   4. Maps those symbols back to their defining files
 *   5. Outputs unique file-to-file edges in expected.json format
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

// Import the SCIP protobuf bindings from scip-typescript
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { scip } = require("@sourcegraph/scip-typescript/dist/src/scip") as {
  scip: {
    Index: {
      deserialize(bytes: Uint8Array): ScipIndex;
    };
    SymbolRole: {
      Definition: number;
      Import: number;
      ReadAccess: number;
      WriteAccess: number;
    };
  };
};

// TypeScript types for SCIP structures (based on protobuf schema)
interface ScipIndex {
  metadata: ScipMetadata;
  documents: ScipDocument[];
  external_symbols: ScipSymbolInformation[];
}

interface ScipMetadata {
  version: number;
  tool_info: {
    name: string;
    version: string;
  };
  project_root: string;
  text_document_encoding: number;
}

interface ScipDocument {
  language: string;
  relative_path: string;
  occurrences: ScipOccurrence[];
  symbols: ScipSymbolInformation[];
}

interface ScipOccurrence {
  range: number[];
  symbol: string;
  symbol_roles: number;
  syntax_kind?: number;
  override_documentation?: string[];
  diagnostics?: unknown[];
  enclosing_range?: number[];
}

interface ScipSymbolInformation {
  symbol: string;
  documentation?: string[];
  relationships?: ScipRelationship[];
}

interface ScipRelationship {
  symbol: string;
  is_reference?: boolean;
  is_implementation?: boolean;
  is_type_definition?: boolean;
  is_definition?: boolean;
}

// Our expected.json edge format
interface ExpectedEdge {
  source: string;
  target: string;
  relation: "imports" | "exports" | "references" | "implements";
}

/**
 * Parse command line arguments
 */
function parseArgs(): { input: string; output: string | null; verbose: boolean } {
  const args = process.argv.slice(2);
  let input: string | null = null;
  let output: string | null = null;
  let verbose = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--input" || args[i] === "-i") {
      input = args[++i];
    } else if (args[i] === "--output" || args[i] === "-o") {
      output = args[++i];
    } else if (args[i] === "--verbose" || args[i] === "-v") {
      verbose = true;
    } else if (args[i] === "--help" || args[i] === "-h") {
      console.log(`
Usage: npx tsx scripts/fixture-tools/scip-to-expected.ts [options]

Options:
  --input, -i   Path to SCIP index file (required)
  --output, -o  Path to output expected.json (default: stdout)
  --verbose, -v Print debug information
  --help, -h    Show this help message
`);
      process.exit(0);
    }
  }

  if (!input) {
    console.error("Error: --input is required");
    process.exit(1);
  }

  return { input, output, verbose };
}

/**
 * Check if a symbol_roles bitmask includes the Definition role
 */
function isDefinition(symbolRoles: number): boolean {
  return (symbolRoles & scip.SymbolRole.Definition) !== 0;
}

/**
 * Check if a symbol_roles bitmask includes the Import role
 */
function isImport(symbolRoles: number): boolean {
  return (symbolRoles & scip.SymbolRole.Import) !== 0;
}

/**
 * Normalize a file path to forward slashes and remove leading ./
 */
function normalizePath(filePath: string): string {
  return filePath.replace(/\\/g, "/").replace(/^\.\//, "");
}

/**
 * Filter external symbols (from node_modules, npm packages, etc.)
 * SCIP symbols have a specific format: scip-typescript npm <package> <version> <path>`<descriptor>
 * Local symbols start with "local " and are file-scoped (should not create cross-file edges)
 */
function isLocalSymbol(symbol: string): boolean {
  // Local symbols like "local 2" are file-scoped identifiers
  // They should NOT create cross-file edges
  return symbol.startsWith("local ");
}

/**
 * Main conversion logic
 */
function convertScipToExpected(indexPath: string, verbose: boolean): ExpectedEdge[] {
  // Read and deserialize the SCIP index
  const indexBytes = readFileSync(indexPath);
  const index: ScipIndex = scip.Index.deserialize(new Uint8Array(indexBytes));

  if (verbose) {
    console.error(`Loaded SCIP index with ${index.documents.length} documents`);
    console.error(`Project root: ${index.metadata?.project_root || "(not set)"}`);
    console.error(`Tool: ${index.metadata?.tool_info?.name} v${index.metadata?.tool_info?.version}`);
  }

  // Phase 1: Build symbol → defining-file map
  // A symbol is "defined" in a file if there's an occurrence with Definition role
  const symbolToDefiningFile = new Map<string, string>();

  for (const doc of index.documents) {
    const filePath = normalizePath(doc.relative_path);

    for (const occ of doc.occurrences) {
      if (isDefinition(occ.symbol_roles) && occ.symbol) {
        // This symbol is defined in this file
        symbolToDefiningFile.set(occ.symbol, filePath);
      }
    }
  }

  if (verbose) {
    console.error(`Found ${symbolToDefiningFile.size} symbol definitions`);
  }

  // Phase 2: For each file, find all symbol references and map to edges
  const edgeSet = new Set<string>();
  const edges: ExpectedEdge[] = [];
  
  // Track edge provenance for debugging
  const edgeProvenance = new Map<string, string[]>();

  for (const doc of index.documents) {
    const sourceFile = normalizePath(doc.relative_path);

    for (const occ of doc.occurrences) {
      // Skip definitions - we only want references
      if (isDefinition(occ.symbol_roles)) {
        continue;
      }
      
      // Skip local symbols - they are file-scoped and should not create cross-file edges
      if (isLocalSymbol(occ.symbol)) {
        continue;
      }

      // Skip symbols without a known definition location
      const targetFile = symbolToDefiningFile.get(occ.symbol);
      if (!targetFile) {
        continue;
      }

      // Skip self-references
      if (sourceFile === targetFile) {
        continue;
      }

      // Determine the relation type
      let relation: ExpectedEdge["relation"];
      if (isImport(occ.symbol_roles)) {
        relation = "imports";
      } else {
        // Could be ReadAccess or WriteAccess - both are "references"
        // For now, we treat imports specially, everything else is "imports"
        // since that's what our expected.json format primarily uses
        relation = "imports";
      }

      // Create a unique edge key to avoid duplicates
      const edgeKey = `${sourceFile}|${targetFile}|${relation}`;
      if (!edgeSet.has(edgeKey)) {
        edgeSet.add(edgeKey);
        edges.push({
          source: sourceFile,
          target: targetFile,
          relation
        });
        edgeProvenance.set(edgeKey, []);
      }
      
      // Track which symbols contribute to this edge
      if (verbose) {
        edgeProvenance.get(edgeKey)!.push(occ.symbol);
      }
    }
  }
  
  // In verbose mode, print edge provenance
  if (verbose) {
    console.error("\nEdge provenance:");
    for (const [edgeKey, symbols] of edgeProvenance.entries()) {
      const uniqueSymbols = [...new Set(symbols)];
      console.error(`  ${edgeKey}:`);
      for (const sym of uniqueSymbols.slice(0, 3)) {
        console.error(`    - ${sym}`);
      }
      if (uniqueSymbols.length > 3) {
        console.error(`    ... and ${uniqueSymbols.length - 3} more`);
      }
    }
  }

  // Sort edges for consistent output
  edges.sort((a, b) => {
    const srcCmp = a.source.localeCompare(b.source);
    if (srcCmp !== 0) return srcCmp;
    const tgtCmp = a.target.localeCompare(b.target);
    if (tgtCmp !== 0) return tgtCmp;
    return a.relation.localeCompare(b.relation);
  });

  if (verbose) {
    console.error(`Generated ${edges.length} file-to-file edges`);
  }

  return edges;
}

/**
 * Main entry point
 */
function main(): void {
  const { input, output, verbose } = parseArgs();

  const inputPath = path.resolve(input);
  const edges = convertScipToExpected(inputPath, verbose);

  const jsonOutput = JSON.stringify(edges, null, 2) + "\n";

  if (output) {
    const outputPath = path.resolve(output);
    writeFileSync(outputPath, jsonOutput, "utf-8");
    console.log(`Wrote ${edges.length} edges to ${outputPath}`);
  } else {
    console.log(jsonOutput);
  }
}

main();
